#docker-compose up  - terminal
version: "4.47.0"
services:
  postgres:
    container_name: accounts_db
    image: postgres
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345"
    ports:
      - "5432:5432"